# -*- coding: utf-8 -*-
"""Functions Practice

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ol2IKFTEH6n-u8QGfonPF8jfdLzHbRSC
"""

#1. Write a Python function to find the Max of three numbers

def max_num(a,b,c):
  if a>b>c:
    print(a)
  if b>c>a:
    print(b)
  if c>a>b:
    print(c)
  return max_num(3,2,1)

def max_num(a,b,c):
  if a>=b and a>=c:
     largest= a
  if b>=c and b>=a:
     largest = b 
  if c>=a and c>=b:
     largest = c
  return largest
print(max_num(2,3,3))

#2. Write a Python function to sum all the numbers in a list

def list_sum(numbers):
  total= 0
  for x in numbers:
    total = total +x 
  return total
print(list_sum((1,2,3)))

# 3Write a Python function to multiply all the numbers in a list

def list_prod(numbers):
  total = 1
  for x in numbers:
      total = total * x 
  return total
print(list_prod((1,9,3)))

#4. Write a Python program to reverse a string

def reverse(s):
  if len(s) == 0:
    return s
  else:
    return s[::-1]
  
print(reverse('ihtreek'))

#5Write a Python function to calculate the factorial of a number (a non-negative integer). 
 #The function accepts the number as an argument.
def fact(n):
  if n==0:
    return 1
  else:
    return n*fact(n-1)
  
n = (int(input('Enter a value:')))
print(fact(n))

#6 Write a Python function to check whether a number falls in a given range.

def num_check(n):
  if n in range(5,10):
    print('Correct Number')
  
  else: 
    print('Wrong number')

n = int(input("Enter the number"))
print(num_check(n))

#7Write a Python function that accepts a string and
# calculate the number of upper case letters and lower case letters

#def upper_lower(sentence):

sentence = 'Keerthi'
New = sentence.upper()
print(New)

def upper_lower(string):
  count1=0
  count2=0
  for i in string:
      if(i.islower()):
            count1=count1+1
      elif(i.isupper()):
            count2=count2+1
  print("The number of lowercase characters is:")
  print(count1)
  print("The number of uppercase characters is:")
  print(count2)

#8 Write a Python function that takes a list 
 #and returns a new list with unique elements of the first list

list1 = [1,2,2,3,3,4,4]
    list_set = set(list1)

#9. Write a Python function that takes a number as a parameter and check the number is prime or not

pass

#10. Write a Python program to print the even numbers from a given list.


def even_num(list):
  #list= [1,2,3,4]
  if list%2 ==0:
        print('Even Number')
  if list%2 !=0:
        print('Not Even Number')

 
        print(even_num([1,2,3,4]))

#12 Check if a given string is a palandrome: 

def palandrome(word):

  if word[0:] == word[::-1]:
    print('palandrome')
  else:
    print('Not a palandrome!')

word = input('Enter a word: ')
print(palandrome(word))

# 13 Write a Python function that prints out the first n rows of Pascal's triangle.

pass

#14 Check if a string is palandrome or not
 
def palandrome(word):
   if word[0:] == word[::-1]:
    print('palandrome')
   else:
    print('Not a palandorme')

word = "The quick brown fox jumps over the lazy dog"
print(palandrome(word))

if __name__ == '__main__':
    for i in range(int(input())):
        name = input()
        score = float(input())

